repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        pass_filenames: false
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy .
        language: system
        types: [ python ]
        pass_filenames: false
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black .
        language: system
        types: [ python ]
        pass_filenames: false
  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: bandit .
        language: system
        types: [ python ]
        pass_filenames: false