name: Deploy to Production

on:
#  push:
#    branches: [main]
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t  example-cicd .
      - name: Login to Docker Hub (or your registry)
        uses: actions/docker/login@v2
        with:
          registry: your-registry-hostname  # Replace with your registry hostname
          username: your-docker-username
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Push Docker image to registry
        run: docker push your-registry-hostname/your-poetry-project:latest