name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install.sh | bash -
      - name: Install dependencies
        run: poetry install
      - name: Run Lint checks
        run: poetry run nox -e lint
      - name: Run Typing checks
        run: poetry run nox -e typing